// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdtyBzEX0K01lMtUngWDZ9ME27BOed4oI',
    appId: '1:1001903181376:android:d9c8dcb42b06e607ee59a5',
    messagingSenderId: '1001903181376',
    projectId: 'medack-8f113',
    storageBucket: 'medack-8f113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB195H-8QpadUZC_zNp5VWbpf-lPLvOvvk',
    appId: '1:1001903181376:ios:6e13b7e159b97297ee59a5',
    messagingSenderId: '1001903181376',
    projectId: 'medack-8f113',
    storageBucket: 'medack-8f113.firebasestorage.app',
    iosBundleId: 'com.example.lab5',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQY258VSxP-FWxnBJBqJlhAd7-QcUfiSU',
    appId: '1:1001903181376:web:807bab01a4dd4682ee59a5',
    messagingSenderId: '1001903181376',
    projectId: 'medack-8f113',
    authDomain: 'medack-8f113.firebaseapp.com',
    storageBucket: 'medack-8f113.firebasestorage.app',
    measurementId: 'G-VHTMW3MPTJ',
  );

}